language: python
python:
  - 3.6
env:
  - DJANGO=2.1 DB=mysql
#before_install:
#  - chmod +x ./setup.py
install:
  - pip install django==$DJANGO --quiet
  - pip install django-nose
  - pip install codecov
  - pip install pylint-django
script:
#  - ./setup.py test
  - python manage.py test
after_success:
  - codecov
  - pylint --load-plugins pylint_django ./lms_app
