# Generated by Django 2.1.3 on 2018-12-08 15:35

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fio',
            new_name='FIO',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_instructors',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='lms_app.Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='groups_of_course',
            field=models.ManyToManyField(blank=True, to='lms_app.Group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trusted_individuals',
            field=models.ManyToManyField(blank=True, related_name='trusted_individuals', to='lms_app.Student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_info',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=uuid.uuid1, max_length=100),
        ),
    ]
